### ISSUE TITLE
Error: Incorrect request format when trying to call /login

### ISSUE THREAD

**Issue by ymhmd** [random42/passport-spid#2]
Hi,

I've just noticed one error happened to me while using `example.ts`. I am not sure the root cause of this issue. Could you please help me to understand the issue?

**Steps**
1. Update `  const idp = 'https://posteid.poste.it'` 
2. Update `privateKey` and `spCert`
3. Update `IPACode` to be `PA:IT-c_h501`
4. Run example `yarn dev`
5. Open `http://localhost:4000/login` in the browser
6. Browser navigates to `https://posteid.poste.it/jod-fs/ssoservicepost` 

**Error**
Error message `messaggio di avvisoErrore: Formato richiesta non corretto - Contattare il gestore del servizio` appears

**Screenshot**
<img width="1181" alt="Screenshot 2023-05-09 at 23 38 58" src="https://github.com/random42/passport-spid/assets/25840233/5ce46616-99e8-4899-b916-bac03fd2d945">

**Comment by Gioppix** [comment]
have you registered the metadata? this is how you would do it in the test env: https://demo.spid.gov.it/validator#/metadata-sp-download

**Comment by ymhmd** [comment]
@Gioppix, thanks a lot for the answer. It worked on test/demo env after I registered the metadata. 

One more question, how can we register the metadata with real IdPs (Poste, Sielte ...etc) ? Maybe some docs can help 🙏

**Comment by Gioppix** [comment]
@ymhmd this is the list of IdPs - https://registry.spid.gov.it/identity-providers . I think you need to find the registration page for each one. May I ask how you updated the privateKey and spCert? I can't get this to work on the test env.

Thanks!

**Comment by ymhmd** [comment]
@Gioppix, To make it work, I did the following steps:
1. Create and validate certificate and private key as per https://github.com/italia/spid-compliant-certificates-python. This step should generate `crt.pem`, `csr.pem` and `key.pem`
2. Update ` const privateKey = (await fs.readFile(`path/key.pem`)).toString();`
3. Update ` const privateKey = (await fs.readFile(`path/crt.pem`)).toString();`

I hope this will make it work for you. If not, please let me know

**Comment by Gioppix** [comment]
@ymhmd what command have you used to start? have you cloned the repo or just the example? thanks

**Comment by ymhmd** [comment]
@Gioppix 
* First, you need to install this python requirement using `pip install spid-compliant-certificates`
* We can generate `crt.pem`, `csr.pem` and `key.pem` with: 
```
 spid-compliant-certificates generator \
    --key-size 3072 \
    --common-name example \
    --days 365 \
    --entity-id YOUR_ENTITY_ID \
    --locality-name Roma \
    --org-id PA:IT-c_h501 \
    --org-name example \
    --sector public
```

* To validate them, please run `spid-compliant-certificates validator --sector public` (the command should be executed in the same directory where `crt.pem`, `csr.pem` and `key.pem` exist

**Comment by Gioppix** [comment]
@ymhmd Sorry I was unclear, I meant the command to start the whole project on localhost

**Comment by ymhmd** [comment]
@Gioppix  To run it locally:
1. Update `dev` script in `package.json` to `ts-node-dev --respawn --inspect=0.0.0.0:9229 -- examples/main.ts`
2. Run `yarn dev`

**Comment by Gioppix** [comment]
@ymhmd thanks a lot!
