### ISSUE TITLE
 Error: Provider 'https://localhost:8443' not found 

### ISSUE THREAD

**Issue by piccinnigius** [random42/passport-spid#3]
` Error: Provider 'https://localhost:8443' not found
 at SpidStrategy.<anonymous> (D:\prj\xxx\node_modules\passport-spid\dist\src\strategy.js:66:23)
`

any  info about this? this happens when i run the example

Thanks in advance
Giuseppe

**Comment by random42** [comment]
You have to setup a local identity provider through the docker image `italia/spid-saml-check`. Look at the docker-compose file. You can run it directly with `docker-compose up` in the repository.
