### ISSUE TITLE
generateSpidServiceProviderMetadata(): generated metadata fails demo.spid.gov.it test #6

### ISSUE THREAD

**Issue by fautore** [random42/passport-spid#8]
Hi, everyone,
as mentioned in the tilte, i got passport-spid to generate and expose the metadata that demo.spid.gov.it will require on authentication, but i seem to encounter an error on metadata validation test number 6 https://demo.spid.gov.it/validator#/metadata-sp-check-strict is it a problem of the passport strategy, or am i configuring someting wrong?

here's the test number 6 error, lemme know if anything else is needed.
```error
failure - value: Description: the metadata signature MUST be valid stderr: func=xmlSecOpenSSLEvpSignatureVerify:file=evp_signatures.c:line=368:obj=rsa-sha256:subj=unknown:error=18:data do not match:details=EVP_VerifyFinal: signature does not verify FAIL SignedInfo References (ok/all): 1/1 Manifests References (ok/all): 0/0 Error: failed to verify file "/tmp/tmp7h86eu2a.xml"
```

**Comment by random42** [comment]
Tests pass with latest `spid-sp-test`, so it seems to be an issue with your certificate. Take a look at `test/docker-compose.yml` to see how the certificate is generated (https://github.com/italia/spid-compliant-certificates).
