### ISSUE TITLE
why is a cache necessary?

### ISSUE THREAD

**Issue by fautore** [random42/passport-spid#9]
Hi all,
basically what the title says, is a cache really necessary? can it be optional?

**Comment by random42** [comment]
An external cache is necessary if your backend runs in a distributed way, on more than one instance. Otherwise you can passa a normal JavaScript Map as documented.

**Comment by fautore** [comment]
what happens if my backend is distributed and i still use a js map?

**Comment by random42** [comment]
One instance may initiate the session but the final redirect may end up on another instance, which does not has the session in cache. I'm closing the issue.
